### ISSUE TITLE
add ajax-progress styles

### ISSUE THREAD

**Issue by 1forh** [skycatchfire/fire#139]
`/assets/styles/components/_ajax-progress.scss`

```scss
.ajax-progress.ajax-progress-fullscreen {
  position: fixed;
  top: 0;
  left: 0;
  z-index: $z-index-loader;
  width: 100%;
  height: 100%;
  display: flex;
  align-items: center;
  justify-content: center;
  background-color: rgba($primary, 0.7);

  &::after {
    content: '';
    width: 100px;
    height: 100px;
    background-image: url(/themes/fire/assets/media/svgs/icon--spinner.svg);
    background-size: contain;
    background-position: center;
    background-repeat: no-repeat;
  }
}
```

`/assets/media/svgs/icon--spinner.svg`

```svg
<svg width="200" height="200" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid" class="lds-rolling" style="background:0 0"><circle cx="50" cy="50" fill="none" stroke="#ffffff" stroke-width="5" r="35" stroke-dasharray="164.93361431346415 56.97787143782138" transform="rotate(209.588 50 50)"><animateTransform attributeName="transform" type="rotate" calcMode="linear" values="0 50 50;360 50 50" keyTimes="0;1" dur="1s" begin="0s" repeatCount="indefinite"/></circle></svg>
```

`assets/styles/base/_variables.scss`

```scss
$z-index-loader: 20001;
```
