### ISSUE TITLE
Clean up local tasks

### ISSUE THREAD

**Issue by BrentWMiller** [skycatchfire/fire#143]
Shrinks font size on mobile and makes sure nothing overflows.

`_local-tasks.scss`
```scss
#block-fire-local-tasks {
  display: flex;
  justify-content: center;
  max-width: 100%;
  padding: 12px 0;
  background-color: $black;

  ul {
    @include reset-list;
    display: flex;

    @include media-breakpoint-down(sm) {
      max-width: 100%;
    }

    li {
      padding: 0 12px;

      @include media-breakpoint-down(sm) {
        padding: 0 8px;
        font-size: 13px;
      }

      a {
        font-weight: bold;
        color: #fff;
      }
    }
  }
}
```

<img width="550" alt="Screen Shot 2020-02-10 at 10 04 07 AM" src="https://user-images.githubusercontent.com/13574057/74161355-cbb19780-4bec-11ea-80c4-aa863021cfe2.png">

**Comment by BrentWMiller** [comment]
Optionally:

`_local-taks.scss`
```scss
#block-fire-local-tasks {
  display: flex;
  justify-content: center;
  max-width: 100%;
  padding: 10px 10px;
  background-color: $black;

  .is-logged-in & {
    z-index: $zindex-fixed;
    position: fixed;
    bottom: 25px;
    left: 25px;
    padding-left: 35px;
    background-color: $black;
    border-radius: 25px;
  }

  ul {
    @include reset-list;
    display: flex;

    @include media-breakpoint-down(sm) {
      max-width: 100%;
    }

    li {
      padding: 0 8px;
      font-size: 13px;

      a {
        font-weight: bold;
        color: $white;

        .is-logged-in & {
          color: $white;
        }
      }
    }
  }
}
```

`admin-toggle.css`
```css
.fire-admin-toggle {
  position: fixed;
  z-index: 10001;
  bottom: 0;
  left: 0;
  display: flex;
  justify-content: center;
  align-items: center;
  width: 30px;
  height: 30px;
  margin: 30px;
  padding: 0;
  text-align: center;
  border: none;
  border-radius: 50%;
  background-color: transparent;
}

[fire-admin-toggle="true"] .fire-admin-toggle {
  background-color: rgba(255, 255, 255, 0.35);
  transition: background-color 0.3s;
}

[fire-admin-toggle="true"] .fire-admin-toggle:hover {
  background-color: #fff;
}

.fire-admin-toggle svg {
  width: 22px;
  height: 22px;
  fill: #fff;
}

[fire-admin-toggle="true"] .fire-admin-toggle svg {
  fill: #000;
}

.fire-admin-toggle-menu-hidden {
  display: none !important;
}

[fire-admin-toggle="true"] {
  padding-top: 0 !important;
}

[fire-admin-toggle="false"] {
  padding-top: 79px !important;
}
```

<img width="330" alt="Screen Shot 2020-02-10 at 11 03 20 AM" src="https://user-images.githubusercontent.com/13574057/74166676-fa337080-4bf4-11ea-9ade-6086731c16db.png">
