### ISSUE TITLE
Style the image crop descriptions

### ISSUE THREAD

**Issue by BrentWMiller** [skycatchfire/fire#149]
They kind of just blend in and get lost.

Add to `styles.css` in fire-seven.
```css
.crop-type-description {
  max-width: 428px;
  padding: 10px;
  margin-bottom: 10px;
  line-height: 19px;
  border: 1px solid #3399fe;
  border-radius: 4px;
  background-color: #e8f2f9;
}
```

<img width="810" alt="Screen Shot 2020-02-17 at 2 14 44 PM" src="https://user-images.githubusercontent.com/13574057/74680931-13f22c00-5190-11ea-8e25-6106e10b0d4d.png">
