### ISSUE TITLE
Switch `maintain-ratio` mixin's attribute order

### ISSUE THREAD

**Issue by BrentWMiller** [skycatchfire/fire#41]
Should be updated to the below. Accept divisor first.

```scss
@mixin maintain-ratio($divisor: 1.43, $dividend: 1) {
  width: 100%;
  padding-bottom: $dividend / $divisor * 100%;
}
```

```scss
@include maintain-ratio(16, 9);
```
