### ISSUE TITLE
Fix for `Drupal is not defined` error

### ISSUE THREAD

**Issue by BrentWMiller** [skycatchfire/fire#54]
In `fire.libraries.yml` add:

```yml
bundle-styles:
  css:
    theme:
      dist/bundle.css: {}
bundle-scripts:
  js:
    dist/bundle.js: {}
  dependencies:
    - core/drupal
    - core/jquery
    - core/drupal.ajax
```
